spring.application.name=history-service
server.port=8082

spring.datasource.url=jdbc:h2:mem:historydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

#CONFIGURAÇÕES POSTGRES (SERÃO USADAS MAIS TARDE)

#spring.datasource.url=jdbc:postgresql://localhost:5432/hospital
#spring.datasource.username=admin
#spring.datasource.password=admin